# SPDX-License-Identifier: Apache-2.0
# (C) Copyright IBM Corporation 2026
 # RPM spec file for the Quantum Resource Management Interface (QRMI)
#
# Package produced:
#   qrmi - shared library (libqrmi.so) and C header (qrmi.h)
#
# Build requirements:
#   - Rust toolchain >= 1.91  (install via rustup; not available as an RPM on EL8/EL9)
#   - cargo-vendor (bundled with cargo)
#   - gcc, make, cmake, openssl-devel, zlib-devel, pkg-config
#
# Offline / air-gapped builds:
#   Run the following once on a machine with internet access to create the
#   vendor tarball, then place it alongside the source tarball:
#
#     tar xf qrmi-%%{qrmi_version}.tar.gz
#     cd qrmi-%%{qrmi_version}
#     cargo vendor vendor
#     tar czf qrmi-%%{qrmi_version}-vendor.tar.gz vendor/
#
# Usage:
#   rpmbuild -ba qrmi.spec \
#     --define "_sourcedir /path/to/sources" \
#     --define "qrmi_version $(grep -m1 '^version' Cargo.toml | sed 's/.*\"\(.*\)\".*/\1/')"
#
# The version is intentionally not hardcoded here. It must be supplied by the
# caller via --define so that Cargo.toml remains the single source of truth.

# Skip debug info generation
%global debug_package %{nil}

Name:           qrmi-devel
Version:        %{qrmi_version}
Release:        1%{?dist}
Summary:        Quantum Resource Management Interface (QRMI)
License:        Apache-2.0
URL:            https://github.com/qiskit-community/qrmi
Source0:        qrmi-%{version}.tar.gz
Source1:        qrmi-%{version}-vendor.tar.gz

Provides:       qrmi-devel = %{version}-%{release}
Provides:       libqrmi.so.0()(64bit)
Provides:       libqrmi.so()(64bit)

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  pkg-config
BuildRequires:  rpm-build


# Rust toolchain is installed via rustup and is not an RPM dependency.
# Ensure `cargo` and `rustc` >= 1.91 are available in PATH before building.

%description
Quantum Resource Management Interface (QRMI) is a set of libraries that
provide a unified interface to control the state of quantum resources.
It exposes a C API (libqrmi.so / qrmi.h) and a Python API built on top
of the same Rust core. This package includes both the shared library and
development files (header) for building applications against the QRMI C API.

# ---------------------------------------------------------------------------
# Prep
# ---------------------------------------------------------------------------
%prep
%autosetup -n qrmi-%{qrmi_version}

# Unpack the vendored Rust dependencies
tar xf %{SOURCE1}

# Configure Cargo to use the vendored sources (offline build)
mkdir -p .cargo
cat > .cargo/config.toml << 'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
%build
# Source the Rust environment if installed via rustup
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Build the shared library
make build

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
%install
install -d %{buildroot}%{_libdir}
install -d %{buildroot}%{_includedir}

# Shared library
install -m 0755 target/release/libqrmi.so \
    %{buildroot}%{_libdir}/libqrmi.so.%{version}
ln -sf libqrmi.so.%{version} \
    %{buildroot}%{_libdir}/libqrmi.so.0
ln -sf libqrmi.so.0 \
    %{buildroot}%{_libdir}/libqrmi.so

# C header (generated by cbindgen during the cargo build)
install -m 0644 qrmi.h \
    %{buildroot}%{_includedir}/qrmi.h

# ---------------------------------------------------------------------------
# Post-install / post-uninstall ldconfig triggers
# ---------------------------------------------------------------------------
%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig

# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------
%files
%license LICENSE.txt
%doc README.md INSTALL.md
%{_libdir}/libqrmi.so.%{version}
%{_libdir}/libqrmi.so.0
%{_libdir}/libqrmi.so
%{_includedir}/qrmi.h

# ---------------------------------------------------------------------------
# Changelog
# ---------------------------------------------------------------------------
%changelog
* Fri Feb 27 2026 Claudio Carvalho <cclaudio@ibm.com> - 0.11.0-1
- Initial RPM packaging