---
# Build python wheels on a specific runner
#
# Workflow inputs:
# - [required] runner
# - [optional] wheel-prefix
#
# Workflow artifacts produced:
# - <prefix>-wheels-<arch>
#
# Workflow dependencies:
# - None. It does not depend on any other workflow.

name: Build wheels
on:
  workflow_call:
    inputs:
      runner:
        description: >-
          Runner that will be used to run the workflow
        type: string
        required: true
      wheel-prefix:
        description: >-
          Prefix for the wheel file name. This is used to distinguish between
          different builds of the same package.
        type: string
        default: "pr"
        required: false

jobs:
  wheels-runner:
    runs-on: ${{ inputs.runner }}
    steps:

    - name: System info
      id: sysinfo
      run: |
        echo "arch=$(uname -m)" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v6

    # We only build for one python version. The abi3 wheel generated
    # is compatible with all other python versions we support.
    - uses: actions/setup-python@v6
      name: Install Python
      with:
        python-version: 3.12

    # The manylinux image has many cpython versions installed.
    - name: Build QRMI wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_PLATFORM: linux
        CIBW_BUILD: cp312-manylinux_${{ steps.sysinfo.outputs.arch }}

    - name: Upload QRMI wheels
      uses: actions/upload-artifact@v6
      if: ${{ success() }}
      with:
        name: ${{ inputs.wheel-prefix }}-wheels-${{ steps.sysinfo.outputs.arch }}
        path: ./wheelhouse/*.whl
        if-no-files-found: error
        retention-days: 1
