---
# This reusable workflow builds the python wheels for the QRMI package.
#
# Workflow inputs:
# - python-version
# - container-image
#
# Workflow artifacts:
# - qrmi-wheel: qrmi-*.whl
#
# Workflow dependencies:
# - None. It does not depend on any other workflow.

name: Build the QRMI wheel
on:
  workflow_call:
    inputs:
      python-version:
        description: >-
          Python version to build the wheels
        type: string
        required: true
      container-image:
        description: >-
          Container image to use for building (e.g., 'registry.access.redhat.com/ubi8/ubi:8.10' or 'ubuntu:24.04')
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container-image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build dependencies
      run: ./tools/install-build-deps.sh

    - name: Get QRMI information
      id: qrmi-info
      run: |
        QRMI_VERSION=$(make get-qrmi-version)
        PYTHON_CP=$(make get-python-cp)
        echo "version=$QRMI_VERSION" >> $GITHUB_OUTPUT
        echo "python_cp=${PYTHON_CP}" >> $GITHUB_OUTPUT

    - name: Get system information
      id: sys-info
      run: |
        ARCH=$(arch)
        PLATFORM=$(make get-platform-id)
        echo "arch=${ARCH}" >> $GITHUB_OUTPUT
        echo "platform=${PLATFORM}" >> $GITHUB_OUTPUT

    - name: Create venv
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}" make create-venv
        echo "PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> ${GITHUB_ENV}

    - name: Build QRMI wheel
      run: make build-python-wheel

    - name: Upload QRMI wheel
      uses: actions/upload-artifact@v6
      if: ${{ success() }}
      with:
        name: qrmi-wheel-${{ steps.qrmi-info.outputs.version }}-${{ steps.qrmi-info.outputs.python_cp }}-${{ steps.sys-info.outputs.platform }}-${{ steps.sys-info.outputs.arch }}
        path: target/wheels/qrmi-${{ steps.qrmi-info.outputs.version }}-${{ steps.qrmi-info.outputs.python_cp }}-*.whl
        if-no-files-found: error
        retention-days: 5
