---
# SPDX-License-Identifier: Apache-2.0
# (C) Copyright IBM Corporation 2026

# This workflow creates a new QRMI release.
#
# Requires:
# - GITHUB_TOKEN secret
#
# Release assets:
# - qrmi-{version}.tar.gz
# - qrmi-{version}-vendor.tar.gz
# - libqrmi-{version}-cp312-el8-x86_64.tar.gz
# - qrmi-wheel-{version}-cp312-*.whl

name: Release
on:
  workflow_dispatch:

jobs:

  valid-qrmi-version:
    if: github.repository_owner == 'qiskit-community'
    name: Check new QRMI version valid
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.qrmi-info.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check new QRMI version valid
        run: make check-new-qrmi-version-valid || exit 1

      - name: Get QRMI information
        id: qrmi-info
        run: |
          QRMI_VERSION=$(make get-qrmi-version)
          echo "version=$QRMI_VERSION" >> $GITHUB_OUTPUT

  create-vendor-tarball:
    if: github.repository_owner == 'qiskit-community'
    name: Create vendor tarball
    needs: [valid-qrmi-version]
    uses: ./.github/workflows/tarball-vendor.yml

  create-libqrmi-tarball:
    if: github.repository_owner == 'qiskit-community'
    name: Create libqrmi tarball
    needs: [valid-qrmi-version]
    uses: ./.github/workflows/tarball-libqrmi.yml
    with:
      container-image: 'registry.access.redhat.com/ubi8/ubi:8.10'

  create-qrmi-wheel-tarball:
    if: github.repository_owner == 'qiskit-community'
    name: Create QRMI wheel tarball
    needs: [valid-qrmi-version]
    uses: ./.github/workflows/tarball-qrmi-wheel.yml
    with:
      python-version: '3.12'
      container-image: 'registry.access.redhat.com/ubi8/ubi:8.10'

  # A draft release has some benefits over directly publishing the release,
  # e.g. if something goes wrong during the artifact upload, we can fix it
  # without users seeing a broken release
  create-draft-release:
    if: github.repository_owner == 'qiskit-community'
    name: Create draft release and populate it with assets
    needs: [valid-qrmi-version, create-vendor-tarball, create-libqrmi-tarball, create-qrmi-wheel-tarball]
    permissions:
      contents: write # required to create a draft release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --draft --generate-notes \
            --title "QRMI v${{ needs.valid-qrmi-version.outputs.version }}" \
            "v${{ needs.valid-qrmi-version.outputs.version }}"
  
      - name: Download artifact - vendor tarball
        uses: actions/download-artifact@v4
        with:
          name: qrmi-vendor-tarball

      - name: Upload to release - vendor tarball
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ needs.valid-qrmi-version.outputs.version }} \
            qrmi-${{ needs.valid-qrmi-version.outputs.version }}-vendor.tar.gz \
            --clobber

      - name: Download artifact - libqrmi tarball for RHEL 8
        uses: actions/download-artifact@v4
        with:
          name: libqrmi-${{ needs.valid-qrmi-version.outputs.version }}-el8-x86_64-tarball

      - name: Upload to release - libqrmi tarball for RHEL 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ needs.valid-qrmi-version.outputs.version }} \
            libqrmi-${{ needs.valid-qrmi-version.outputs.version }}-el8-x86_64.tar.gz \
            --clobber

      - name: Download artifact - QRMI wheel tarball for RHEL 8, Python 3.12
        uses: actions/download-artifact@v4
        with:
          name: qrmi-${{ needs.valid-qrmi-version.outputs.version }}-cp312-el8-x86_64-tarball

      - name: Upload to release - QRMI wheel tarball for RHEL 8, Python 3.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ needs.valid-qrmi-version.outputs.version }} \
            qrmi-${{ needs.valid-qrmi-version.outputs.version }}-cp312-el8-x86_64.tar.gz \
            --clobber
    
  publish-release:
    if: github.repository_owner == 'qiskit-community'
    name: Publish release
    needs: [valid-qrmi-version,create-draft-release]
    permissions:
      contents: write # This is required to publish the draft release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Make the release live on github
        gh release edit v${{ needs.valid-qrmi-version.outputs.version }} --verify-tag --draft=false
