---
# This reusable workflow unittest all the Rust code
#
# Workflow inputs:
# - container-image
#
# Workflow artifacts produced:
# - None
#
# Workflow dependencies:
# - None. It does not depend on any other workflow.

name: Unittest QRMI Rust code
on:
  workflow_call:
    inputs:
      container-image:
        description: >-
          Container image to use for building (e.g., 'registry.access.redhat.com/ubi8/ubi:8.10' or 'ubuntu:24.04')
        type: string
        required: true
env:
  CARGO_TERM_COLOR: always
jobs:
  unittest:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container-image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install build dependencies
      run: ./tools/install-build-deps.sh

    - name: Unittest all the rust code
      run: make test-rust-all
