---
# This reusable workflow runs Python unittests on the QRMI wheels package.
#
# Workflow inputs:
# - python-version
# - container-image
#
# Workflow artifacts produced:
# - None
#
# Workflow dependencies:
# - qrmi-wheel

name: Unittest the QRMI Python code
on:
  workflow_call:
    inputs:
      python-version:
        description: >-
          Python version to be used to unittest the code
        type: string
        required: true
      container-image:
        description: >-
          Container image to use for building (e.g., 'registry.access.redhat.com/ubi8/ubi:8.10' or 'ubuntu:24.04')
        type: string
        required: true
jobs:
  unittest:
    runs-on: ubuntu-24.04
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.10
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build dependencies
      run: ./tools/install-build-deps.sh

    - name: Get QRMI version
      id: qrmi-version
      run: |
        QRMI_VERSION=$(make --no-print-directory get-qrmi-version)
        echo "value=${QRMI_VERSION}" >> ${GITHUB_OUTPUT}

    - name: Get distro platform id
      id: distro-platform-id
      run: |
        PLATFORM_ID=$(make --no-print-directory get-distro-platform-id)
        echo "value=${PLATFORM_ID}" >> ${GITHUB_OUTPUT}

    - name: Download QRMI wheels
      uses: actions/download-artifact@v6
      with:
        name: qrmi-wheel-${{ steps.qrmi-version.outputs.value }}-py${{ inputs.python-version }}-${{ steps.distro-platform-id.outputs.value }}
        path: target/wheels/

    - name: Create venv
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}" make create-venv
        echo "PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> ${GITHUB_ENV}

    - name: Install QRMI wheels
      run: make install-python-wheel

    - name: Unittest with pytest
      run: make test-python-wheel
